# Imaging parameters
Imaging:
  RES: [66, 50, 100]
  FOV: [0.1325, 0.1, 0.2] # in meters
  T2star: 254.0           # in milliseconds
  VENC: 1.5               # in meters per second
  TIMESPACING: 30.0       # in milliseconds
  OVERSAMPLING: 2

# Data formatting
Formatting:
  tx: -1.57079633 # -pi/2
  ty: -0.07853982 # -pi/40
  tz: 0.78539816  # pi/4

# EPI parameters
EPI:
  LinesPerShot: 5

# Gradient-echo parameters
FFE:
  LinesPerShot: 1
  
# Spiral parameters
SPIRAL:

# Radial parameters
RADIAL: