# Imaging parameters
Imaging:
  RES: [66, 55, 120]
  FOV: [0.132, 0.11, 0.24] # in meters
  T2star: 254.0            # in milliseconds
  VENC: [1.5, 2.0, 2.5]    # in meters per second
  TIMESPACING: 31.858      # in milliseconds
  OVERSAMPLING: 2

# Data formatting
Formatting:
  tx: 0.0
  ty: 0.0
  tz: -1.57079633 # pi/2

# EPI parameters
EPI:
  LinesPerShot: 5

# Gradient-echo parameters
FFE:
  LinesPerShot: 1

# Spiral parameters
SPIRAL:

# Radial parameters
RADIAL:
