# Imaging parameters
Imaging:
  RES: [66, 40, 1] #[66, 40, 113]
  FOV: [0.132, 0.08, 0.008] #[0.132, 0.08, 0.226] # meters
  T2star: 254.0             # milliseconds
  VENC: 2.5                 # meters per second
  TIMESPACING: 31.858       # milliseconds
  OVERSAMPLING: 2

# Hardware parameters
Hardware:
  G_sr: 195.0    # in mT/m/s
  G_max: 40.0    # in mT/m
  r_BW: 153.0e+3 # in Hz (equivalent to 450 Hz/pixel)

# Imaging orientation (make sure about orthogonality)
Formatting:
  # Data taken from Box paraview filter
  theta_x: 0.0    # degrees
  theta_y: 0.0    # degrees
  theta_z: 90.0   # degrees
  LOC: [-0.063242, 0.012783, -0.07] #[-0.063242, 0.012783, -0.0898078]

# EPI parameters
EPI:
  LinesPerShot: 5

# Gradient-echo parameters
FFE:
  LinesPerShot: 1

# Spiral parameters
SPIRAL:

# Radial parameters
RADIAL:
