# Imaging parameters
Imaging:
  RES: [30, 30, 20]
  FOV: [0.132, 0.11, 0.24] # in meters
  T2star: 254.0            # in milliseconds
  VENC: [1.5, 2.0, 2.5]    # in meters per second
  TIMESPACING: 31.858      # in milliseconds
  OVERSAMPLING: 2

# Hardware parameters
Hardware:
  G_sr: 195.0    # in mT/m/s
  G_max: 40.0    # in mT/m
  r_BW: 153.0e+3 # in Hz (equivalent to 450 Hz/pixel)

# Imaging orientation (make sure about orthogonality)
Formatting:
  M: [1.0, 0.0, 0.0]
  P: [0.0, 0.0, 1.0]
  S: [0.0, 1.0, 0.0]

# # Data formatting
# Formatting:
#   tx: 0.0
#   ty: 0.0
#   tz: -1.57079633 # pi/2

# EPI parameters
EPI:
  LinesPerShot: 5

# Gradient-echo parameters
FFE:
  LinesPerShot: 1

# Spiral parameters
SPIRAL:

# Radial parameters
RADIAL:
