# Imaging parameters
Imaging:
  RES: [66, 40, 113]
  FOV: [0.132, 0.08, 0.226] # in meters
  T2star: 254.0            # in milliseconds
  VENC: [1.5, 2.0, 2.5]    # in meters per second
  TIMESPACING: 31.858      # in milliseconds
  OVERSAMPLING: 2

# Hardware parameters
Hardware:
  G_sr: 195.0    # in mT/m/s
  G_max: 40.0    # in mT/m
  r_BW: 153.0e+3 # in Hz (equivalent to 450 Hz/pixel)

# Imaging orientation (make sure about orthogonality)
Formatting:
  # M_ORI: [0.0, 1.0, 0.0]
  # P_ORI: [1.0, 0.0, 0.0]
  # S_ORI: [0.0, 0.0, 1.0]
  # Data taken from Box paraview filter
  theta_x: 0.0    # degrees
  theta_y: 0.0    # degrees
  theta_z: 90.0  # degrees
  LOC: [-0.063242, 0.012783, -0.0898078]

# EPI parameters
EPI:
  LinesPerShot: 5

# Gradient-echo parameters
FFE:
  LinesPerShot: 1

# Spiral parameters
SPIRAL:

# Radial parameters
RADIAL:
